version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        API_URL: $API_URL
    ports:
      - "80:3000"
    networks:
      app-network:
        ipv4_address: 172.19.0.2
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DB_URI: $MONGODB_URI
    ports:
      - "8080:8080"
    networks:
      app-network:
        ipv4_address: 172.19.0.3

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
