version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        API_URL: http://localhost:8080
    ports:
      - "80:3000"
    networks:
      - app-network
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DB_URI: ${MONGODB_URI}
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
