import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
export default function Login() {
  const backendUrl = process.env.NEXT_PUBLIC_API_URL;
  const router = useRouter();
  const [username, setUsername] = useState<string>("");
  const [password, setPassword] = useState<string>("");
  const [isLoggedin, setIsLoggedin] = useState<boolean>(false);

  function login() {
    fetch(`http://${backendUrl}login`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        Username: username,
        Password: password
      })
    }).then(response => {
      return response.json();
    }).then(data => {
      console.log(data);
      setIsLoggedin(true);
    }).catch(error => {
      console.error(error);
    });
  }
  
  async function fetchRoot() {
    try {
      const response = await fetch(`http://${backendUrl}conntest`);
      const data = await response.json();
      console.log(data);
    } catch (error) {
      console.error(error);
    }
  }

  useEffect(() => {
    if (isLoggedin) {
      router.push("/")
    }
  })

  return (
    <>
      <Head>
        <title>Login to GraphForms</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{fontFamily:"'Poppins', sans-serif"}} className='bg-white'>
        <div id='navbar' className='flex text-center py-5'>
          <p onClick={()=>router.push('/')} className='mx-auto font-medium text-xl'>GraphForms</p>
        </div>
        <div id='body' className='mt-[10vh] text-center'>
          <p className='font-medium text-5xl'>Welcome back.</p>
          <div className='flex'>
            <div id='form' className='mx-auto mt-[10vh]'>
              <input className='bg-[#F2F2F2] border-b border-black p-2 rounded-xl w-[25vw]' placeholder='Username'/><br></br>
              <input className='mt-[5vh] border-b border-black bg-[#F2F2F2] p-2 rounded-xl w-[25vw]' placeholder='Password'/><br></br>
              <button className='mt-[8vh] bg-black text-white text-[18px] rounded-xl py-1 px-10'>Login.</button>
            </div>
          </div>
          <p className='mt-[1vh] font-medium text-center'>or</p>
          <button onClick={()=>router.push('/register')}className='mt-[1vh] border border-black text-[15px] rounded-2xl py-1 px-6'>Register an account.</button>
        </div>
  
      </div>
    </>
  )
}
