import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';

export default function Register() {
  const backendUrl = process.env.NEXT_PUBLIC_API_URL;
  const router = useRouter();
  const [username, setUsername] = useState<string>("");
  const [password, setPassword] = useState<string>("");
  const [isRegistered, setIsRegistered] = useState<boolean>(false);

  function register() {
    fetch(`http://${backendUrl}register`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        Username: username,
        Password: password
      })
    }).then(response => {
      return response.json();
    }).then(data => {
      console.log(data);
      setIsRegistered(true);
    }).catch(error => {
      console.error(error);
    });
  }
  
  async function fetchRoot() {
    try {
      const response = await fetch(`http://${backendUrl}conntest`);
      const data = await response.json();
      console.log(data);
    } catch (error) {
      console.error(error);
    }
  }

  useEffect(() => {
    if (isRegistered) {
      router.push('/login');
    }
  }, [isRegistered, router]);

  return (
    <>
      <Head>
        <title>Register to GraphForms</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{fontFamily:"'Poppins', sans-serif"}} className='bg-white'>
        <div id='navbar' className='flex text-center py-5'>
          <p onClick={()=>router.push('/')} className='mx-auto font-medium text-xl'>GraphForms</p>
        </div>
        <div id='body' className='mt-[10vh] text-center'>
          <p className='font-medium text-5xl'>Register an account.</p>
          <div className='flex'>
            <div id='form' className='mx-auto mt-[10vh]'>
            <input
              className='bg-[#F2F2F2] border-b border-black p-2 rounded-xl w-[25vw]'
              placeholder='Username'
              value={username}
              onChange={(e) => setUsername(e.target.value)}
            />
            <input
              className='mt-[5vh] border-b border-black bg-[#F2F2F2] p-2 rounded-xl w-[25vw]'
              placeholder='Password'
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
              <button className='mt-[8vh] bg-black text-white text-[18px] rounded-xl py-1 px-10'>Register.</button>
            </div>
          </div>
          <p className='mt-[1vh] font-medium text-center'>or</p>
          <button onClick={()=>router.push('/login')}className='mt-[1vh] border border-black text-[15px] rounded-2xl py-1 px-6'>Login to your account.</button>
        </div>
  
      </div>
    </>
  )
}
