import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import { ToastContainer } from 'react-toastify';
import { setToken, clearToken } from '../store/reducers/authSlice';
import { useDispatch, useSelector } from 'react-redux';
import 'react-toastify/dist/ReactToastify.css';

export default function Test() {
  const backendUrl: string = process.env.NEXT_PUBLIC_API_URL!;
  const router = useRouter();
  const dispatch = useDispatch();
  const count = useSelector((state: { count: number }) => state.count);
  
  
  async function fetchRoot() {
    try {
      const response = await fetch(`http://${backendUrl}conntest`);
      const data = await response.json();
      console.log(data);
    } catch (error) {
      console.error(error);
    }
  }

  return (
    <>
      <Head>
        <title>GraphForms</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{fontFamily:"'Poppins', sans-serif"}} className='bg-white'>
        <ToastContainer/>
        <div id='navbar' className='flex text-center py-5'>
          <p onClick={()=>router.push('/')} className='mx-auto font-medium text-xl'>GraphForms</p>
        </div>
        <div id='body' className='mt-[10vh] text-center'>
            <p>Graphforms test</p>
            <button onClick={() => dispatch(setToken('my_token'))}>Set Token</button>
            &nbsp;
            <button onClick={() => dispatch(clearToken())}>Clear Token</button>
        </div>
      </div>
    </>
  )
}
