import { useState } from "react"
import Head from "next/head";
import { ToastContainer, toast } from "react-toastify";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";

export default function Updates() {
    const [updates, setUpdates] = useState();

    return (
        <>
      <Head>
        <title>Updates - GraphForms</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{fontFamily:"'Poppins', sans-serif"}} className='bg-white'>
        <ToastContainer/>
        <Sidebar />
        <Navbar />
        <div id='body' className='mt-[10vh] text-center'>
          <p className='font-semibold text-5xl'>Updates</p>
          {/* <button className="mt-5 mb-1 rounded-2xl bg-blue-500 px-3 text-white font-semibold">Write Update</button> */}
          <div className='flex'>
            <div className='mx-auto w-1/2 border-b-4 mb-5'></div>
            </div>
            <div id='updates'>
                <div className='flex'>
                    <div className='w-1/2 mx-auto text-center'>
                    <p className='font-semibold text-3xl mt-2 mb-2'>Update 1</p>
                    <p className='text-left font-medium text-[#444444]'>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at ultricies turpis. Quisque feugiat ex sit amet eros cursus aliquet. Mauris facilisis tristique tempor. Curabitur ornare dolor ut nulla mollis rutrum. Vestibulum quis volutpat erat. Etiam purus sapien, tincidunt a eros pulvinar, viverra tincidunt enim. Phasellus a lobortis ligula. Quisque pretium vitae odio in tempor. Suspendisse ac dapibus nulla, eget dignissim lacus. Morbi mi ipsum, tincidunt vitae ligula id, hendrerit vulputate odio.
                    </p>        
                    </div>
                </div>
                 </div>
        </div>
      </div>
    </>
    )
}