import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Sidebar from 'components/sidebar';

export default function Createform() {
  const backendUrl: string = process.env.NEXT_PUBLIC_API_URL!;
  const [numofqs, setNumofqs] = useState<number>(1)
  const router = useRouter();

  async function fetchRoot() {
    try {
      const response = await fetch(`http://${backendUrl}conntest`);
      const data = await response.json();
      console.log(data);
    } catch (error) {
      console.error(error);
    }
  }

  return (
    <>
      <Head>
        <title>GraphForms</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{fontFamily:"'Poppins', sans-serif"}} className='bg-white'>
        <ToastContainer/>
        <Sidebar/>
        <div id='navbar' className='flex text-center py-5'>
          <p onClick={()=>router.push('/hub')} className='mx-auto font-medium text-xl'>GraphForms</p>
        </div>
        <div id='body' className='mt-[10vh] px-[25%] text-center'>
            <input className='text-3xl sm:text-5xl text-center font-bold' placeholder='Form title'></input><br/>
            <textarea
              className='w-full text-xl text-slate-500 text-center font-bold mb-5'
              placeholder='Form description'
              rows={3}
            ></textarea>
            <div id='form' className='text-center'>
              {Array.from({ length: numofqs }, (_, i) => (
                <div key={i} className='flex text-2xl font-bold'>
                    <p>{i+1}.</p>
                    <input className='text-2xl ml-5 font-semibold' placeholder='Ask a question.'></input>
                </div>
              ))}
            </div>
            <button onClick={()=>setNumofqs(numofqs+1)} className="bg-black text-white font-bold py-2 px-4 rounded mt-4">
              +
            </button>
        </div>
      </div>
    </>
  )
}
