import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Sidebar from 'components/sidebar';

export default function Workspace() {
  const backendUrl: string = process.env.NEXT_PUBLIC_API_URL!;
  const router = useRouter();

  async function fetchRoot() {
    try {
      const response = await fetch(`http://${backendUrl}conntest`);
      const data = await response.json();
      console.log(data);
    } catch (error) {
      console.error(error);
    }
  }

 

  return (
    <>
      <Head>
        <title>GraphForms</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{fontFamily:"'Poppins', sans-serif"}} className='bg-white'>
        <ToastContainer/>
        <Sidebar/>
        <div id='navbar' className='flex text-center py-5'>
          <p onClick={()=>router.push('/hub')} className='mx-auto font-medium text-xl'>GraphForms</p>
        </div>
        <div id='body' className='mt-[10vh] text-center'>
          <p className='text-center font-bold text-4xl'>My forms.</p>
          <p className='text-center text-[#444444] mb-10 font-medium text-xl'>Create new forms or view older forms here.</p>

          <div className='flex'>
            <div className='mx-auto border-slate-300 border-t-2 border-b-2 mb-5 w-1/2'>
            {/* insert code for retrieving all forms by user*/}
            <p>test</p>
            </div>
          </div>
            <button onClick={()=>router.push('/workspace/createform')} className='bg-black px-2 py-5 rounded-xl text-white w-1/2 font-semibold'>Create a new form.</button>
        </div>
      </div>
    </>
  )
}
