//@ts-nocheck
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Sidebar from 'components/sidebar';
import Link from 'next/link';
import Navbar from '@/components/navbar';

export default function Workspace() {
  const backendUrl: string = process.env.NEXT_PUBLIC_API_URL!;
  const router = useRouter();
  const [forms, setForms] = useState();

  async function fetchForms() {
  let token = null;
  let username = null;
  if (typeof window !== 'undefined') {
    token = localStorage.getItem('token');
    username = localStorage.getItem('username');
  }
  try {
    const response = await fetch(`${backendUrl}yourforms`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        username: username
      })
    });
    const data = await response.json();
    console.log(data);
    setForms(data);
  } catch (error) {
    console.error(error)
  }
}

useEffect(()=>{
  if (!forms) {
    fetchForms()
  }
}, [fetchForms])
 
  return (
    <>
      <Head>
        <title>GraphForms</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ fontFamily: "'Poppins', sans-serif" }} className="bg-white">
        <ToastContainer />
        <Sidebar />
        <Navbar />
        <div id="body" className="mt-[10vh] text-center">
          <p className="text-center font-bold text-4xl">My forms</p>
          <p className="mt-2 text-center text-[#444444] mb-10 font-medium text-xl">
            Create new forms or view older forms here.
          </p>
          <button
            onClick={() => router.push('/workspace/createform')}
            className="bg-black px-2 py-5 rounded-xl text-white w-1/2 font-semibold mb-5"
          >
            Create a new form.
          </button>

          <div className="flex justify-center">
                {forms && forms.forms && forms.forms.length > 0 ? (
                  <div className="mb-2 grid grid-cols-1 md:grid-cols-3 gap-4 w-1/2">
                    {forms.forms.reverse().map((form: any) => (
                      <div key={form.id} className="border border-gray-300 p-4 mb-4 rounded-xl">
                        <h2 className="text-xl font-bold">{form.name}</h2>
                        <div onClick={() => router.push(`/viewform/${form.id}`)} className='rounded text-sm bg-blue-500 text-white inline-block px-2 py-1'>View</div>
                        <div onClick={() => router.push(`/workspace/settings/${form.id}`)} className='rounded text-sm bg-slate-800 text-white inline-block px-2 py-1'>Settings</div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="mb-2 grid grid-cols-1 md:grid-cols-3 gap-4 w-1/2">
                    <p className="border-2 border-dotted border-blue-300 p-4 mb-4 rounded-xl text-center font-semibold text-lg">You have no forms. Create one!</p>
                  </div>
                )}
                </div>
          
        </div>
      </div>
   </>
  )}