name: Deploy GraphForms Backend to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
      
    - name: Initialize Go module
      run: go mod init github.com/monccciii/backend
      
    - name: Build Go application
      run: |
        cd backend
        go build -o bin/application

    - name: Deploy to AWS Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name Graphforms \
          --version-label Graphforms-Backend-${{ env.GITHUB_SHA }} \
          --source-bundle S3Bucket=Graphforms,S3Key=Graphforms-Backend-${{ env.GITHUB_SHA }}.zip

        aws elasticbeanstalk update-environment \
          --environment-name Graphforms-Prod \
          --version-label Graphforms-Backend-${{ env.GITHUB_SHA }}
