name: Deploy GF to AWS
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

     # - name: Setup Go
      # uses: actions/setup-go@v3
      #  with:
      #    go-version: 1.19.6

     # - name: Download dependencies
      #  run: cd backend && go mod download

    #  - name: Start backend server
   #     run: cd backend && go run main.go

     # - name: Run tests
      #  run: cd tests/backend && go mod init github.com/monccciii/graphforms/test && go test -v

      #- name: Stop backend server
       # run: pkill -f "go run main.go"


      - name: Generate frontend deployment package
        run: cd frontend && zip -r ../${{ github.sha }}-frontend.zip .

      - name: Generate backend deployment package
        run: cd backend && zip -r ../${{ github.sha }}-backend.zip .

      - name: Deploy frontend to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Graphforms
          environment_name: Graphforms-Frontend
          version_label: ${{ github.sha }}-frontend
          region: us-east-1
          deployment_package: ${{ github.sha }}-frontend.zip
          use_existing_version_if_available: true

      - name: Deploy backend to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Graphforms
          environment_name: Graphforms-backend
          version_label: ${{ github.sha }}-backend
          region: us-east-1
          deployment_package: ${{ github.sha }}-backend.zip

